Update jell.yml

diff --git a/.github/workflows/jell.yml b/.github/workflows/jell.yml
--- a/.github/workflows/jell.yml
+++ b/.github/workflows/jell.yml
@@ -38,29 +38,55 @@ jobs:
         sudo timedatectl set-timezone "Asia/Shanghai"
         ( sudo -E apt-get -qq install rename ) &
 
-    - name: Syn jell 
-      run: | 
-       shopt -s extglob
-       git rm -r --cache * >/dev/null 2>&1 & 
-       rm -rf `find ./* -maxdepth 0 -type d ! -name ".github/diy"` >/dev/null 2>&1
-       function git_clone() ( 
-         git clone --depth 1 "$1" "$2" || true
-       )
-       function git_sparse_clone() (  
-         branch="$1" rurl="$2" localdir="$3" && shift 3
-        git clone -b "$branch" --depth 1 --filter=blob:none --sparse "$rurl" "$localdir"
-         cd "$localdir"
-         git sparse-checkout init --cone
-         git sparse-checkout set "$@"
-         mv -n "$@" ../
-         cd ..
-         rm -rf "$localdir"
-       )
-       function mvdir() {  
-         mv -n `find "$1"/* -maxdepth 0 -type d` ./
-         rm -rf "$1"
-       }
-       (    
+    - name: Syn jell
+      run: |
+        shopt -s extglob
+        set +e
+        git rm -r --cache * >/dev/null 2>&1 &
+        rm -rf `find ./* -maxdepth 0 -type d ! -name ".github/diy"` >/dev/null 2>&1
+    
+        function git_clone() {
+          git clone --depth 1 $1 $2
+          if [ "$?" != 0 ]; then
+            echo "error on $1"
+            pid="$( ps -q $$ )"
+            kill $pid
+          fi
+        }
+    
+        function git_sparse_clone() {
+          trap 'rm -rf "$tmpdir"' EXIT
+          branch="$1" curl="$2" && shift 2
+          rootdir="$PWD"
+          tmpdir="$(mktemp -d)" || exit 1
+          if [ ${#branch} -lt 10 ]; then
+            git clone -b "$branch" --depth 1 --filter=blob:none --sparse "$curl" "$tmpdir"
+            cd "$tmpdir"
+          else
+            git clone --filter=blob:none --sparse "$curl" "$tmpdir"
+            cd "$tmpdir"
+            git checkout $branch
+          fi
+          if [ "$?" != 0 ]; then
+            echo "error on $curl"
+            exit 1
+          fi
+          git sparse-checkout init --cone
+          git sparse-checkout set "$@"
+          mv -n $@ $rootdir/ || true
+          cd $rootdir
+         }
+    
+        function mvdir() {
+          mv -n `find $1/* -maxdepth 0 -type d` ./
+          rm -rf $1
+        }
+    
+        (
+        git_clone https://github.com/kiddin9/my-packages && mvdir my-packages
+        git_clone https://github.com/kiddin9/openwrt-bypass && mvdir openwrt-bypass
+        git_clone https://github.com/kiddin9/luci-app-dnsfilter
+        )
         git_clone https://github.com/kiddin9/my-packages && mvdir my-packages
         #git_clone https://github.com/kiddin9/openwrt-bypass && mvdir openwrt-bypass
         git_clone https://github.com/kiddin9/luci-app-dnsfilter
