API rate limit exceeded

diff --git a/.github/workflows/jell.yml b/.github/workflows/jell.yml
--- a/.github/workflows/jell.yml
+++ b/.github/workflows/jell.yml
@@ -35,58 +35,59 @@ jobs:
         git config --global user.name "action"
         sudo timedatectl set-timezone "Asia/Shanghai"
 
-    - name: Set git identity
-      run : |
-        git config --global user.email "github-actions[bot]@users.noreply.github.com"
-        git config --global user.name "github-actions[bot]"
-        sudo timedatectl set-timezone "Asia/Shanghai"
-
     - name: Syn jell
-      run: |
+      run : |
         shopt -s extglob
         set +e
         git rm -r --cache * >/dev/null 2>&1 &
         rm -rf `find ./* -maxdepth 0 -type d ! -name ".github/diy"` >/dev/null 2>&1
+    
         function git_clone() {
           git clone --depth 1 $1 $2
           if [ "$?" != 0 ]; then
             echo "error on $1"
-            pid="$( ps -q $$ )"
-            kill $pid
+            exit 1
           fi
         }
+    
         function git_sparse_clone() {
-        trap 'rm -rf "$tmpdir"' EXIT
-        branch="$1" curl="$2" && shift 2
-        rootdir="$PWD"
-        tmpdir="$(mktemp -d)" || exit 1
-        if [ ${#branch} -lt 10 ]; then
-        git clone -b "$branch" --depth 1 --filter=blob:none --sparse "$curl" "$tmpdir"
-        cd "$tmpdir"
-        else
-        git clone --filter=blob:none --sparse "$curl" "$tmpdir"
-        cd "$tmpdir"
-        git checkout $branch
-        fi
-        if [ "$?" != 0 ]; then
-            echo "error on $curl"
-            exit 1
-        fi
-        git sparse-checkout init --cone
-        git sparse-checkout set "$@"
-        mv -n $@ $rootdir/ || true
-        cd $rootdir
+          trap 'rm -rf "$tmpdir"' EXIT
+          branch="$1" curl="$2" && shift 2
+          rootdir="$PWD"
+          tmpdir="$(mktemp -d)" || exit 1
+          
+          # Clone repo based on branch length
+          if [ ${#branch} -lt 10 ]; then
+            git clone -b "$branch" --depth 1 --filter=blob:none --sparse "$curl" "$tmpdir"
+            cd "$tmpdir"
+          else
+            git clone --filter=blob:none --sparse "$curl" "$tmpdir"
+            cd "$tmpdir"
+            git checkout $branch
+          fi
+    
+          if [ "$?" != 0 ]; then
+              echo "error on $curl"
+              exit 1
+          fi
+    
+          git sparse-checkout init --cone
+          git sparse-checkout set "$@"
+          mv -n $@ $rootdir/ || true
+          cd $rootdir
         }
+    
         function mvdir() {
-        mv -n `find $1/* -maxdepth 0 -type d` ./
-        rm -rf $1
+          mv -n `find $1/* -maxdepth 0 -type d` ./
+          rm -rf $1
         }
-        (
-        git_clone https://github.com/kiddin9/my-packages && mvdir my-packages
-        #git_clone https://github.com/kiddin9/openwrt-bypass && mvdir openwrt-bypass
-        git_clone https://github.com/kiddin9/luci-app-dnsfilter
-        git_clone https://github.com/kiddin9/aria2
-        git_clone https://github.com/kiddin9/luci-theme-edge
+    
+        # Clone repositories
+        git_clone https://github.com/kiddin9/my-packages my-packages && mvdir my-packages
+        #git_clone https://github.com/kiddin9/openwrt-bypass openwrt-bypass && mvdir openwrt-bypass
+        git_clone https://github.com/kiddin9/luci-app-dnsfilter luci-app-dnsfilter
+        git_clone https://github.com/kiddin9/aria2 aria2
+        git_clone https://github.com/kiddin9/luci-theme-edge luci-theme-edge
         git_clone https://github.com/kiddin9/autoshare && mvdir autoshare
         git_clone https://github.com/kiddin9/luci-app-xlnetacc
         git_clone https://github.com/kiddin9/luci-app-wizard
